FROM --platform=linux/amd64 golang:1.19 as build
WORKDIR /src/
COPY . /src/
RUN make build
RUN curl -LO https://raw.githubusercontent.com/microsoft/SDN/master/Kubernetes/windows/hns.psm1

FROM --platform=windows/amd64 mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:v1.0.0
COPY --from=build /src/output/kpng.exe /kpng.exe
COPY --from=build /src/*.psm1 /
ADD deploy/start-kpng.ps1 /
WORKDIR /
ENTRYPOINT ["kpng.exe"]
